volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
  jwtdown-db-data:
    external: true
services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jamesyi803@gmail.com
      PGADMIN_DEFAULT_PASSWORD: james
      PGADMIN_DISABLE_POSTFIX: 1
  books:
    build:
      context: ./books
      dockerfile: ./Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./books:/app
    environment:
      DATABASE_URL: postgresql://books:password@postgres/books
      WAIT_HOSTS: postgres:5432
  accounts:
    build:
      context: ./accounts
      dockerfile: ./Dockerfile.dev
    ports:
      - "8200:8000"
    volumes:
      - ./accounts:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: lynnoliviafloyd
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts,books
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000

