volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
  jwtdown-db-data:
    external: true

services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nd@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nd
      PGADMIN_DISABLE_POSTFIX: 1
  nd:
    build:
      context: ./nd
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./nd:/app
    environment:
      DATABASE_URL: postgresql://nd:nd@postgres/nd
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: lynnoliviafloyd
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nd
      - POSTGRES_USER=nd
      - POSTGRES_PASSWORD=nd
    ports:
      - 15432:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: https://localhost:3000
      REACT_APP_ND_API_HOST: https://localhost:8000
